CREATE TYPE "public"."upside_bill_status" AS ENUM('draft', 'pending', 'scheduled', 'paid');--> statement-breakpoint
CREATE TYPE "public"."upside_card_status" AS ENUM('active', 'frozen', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."upside_card_type" AS ENUM('virtual', 'physical');--> statement-breakpoint
CREATE TYPE "public"."upside_reimbursement_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."upside_transaction_status" AS ENUM('pending', 'completed', 'declined');--> statement-breakpoint
CREATE TABLE "upside_bill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_bill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"vendorName" varchar(256) NOT NULL,
	"amount" integer NOT NULL,
	"status" "upside_bill_status" DEFAULT 'pending' NOT NULL,
	"dueDate" timestamp with time zone NOT NULL,
	"invoiceNumber" varchar(128),
	"category" varchar(128) NOT NULL,
	"paidAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_card" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_card_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"last4" varchar(4) NOT NULL,
	"cardName" varchar(256) NOT NULL,
	"type" "upside_card_type" DEFAULT 'virtual' NOT NULL,
	"status" "upside_card_status" DEFAULT 'active' NOT NULL,
	"spendLimit" integer DEFAULT 500000 NOT NULL,
	"currentSpend" integer DEFAULT 0 NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_merchant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_merchant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"category" varchar(128) NOT NULL,
	"logoUrl" varchar(512)
);
--> statement-breakpoint
CREATE TABLE "upside_reimbursement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_reimbursement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"amount" integer NOT NULL,
	"description" varchar(512) NOT NULL,
	"status" "upside_reimbursement_status" DEFAULT 'pending' NOT NULL,
	"category" varchar(128) NOT NULL,
	"receiptUrl" varchar(512),
	"submittedAt" timestamp with time zone NOT NULL,
	"reviewedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "upside_transaction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_transaction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cardId" integer NOT NULL,
	"merchantId" integer NOT NULL,
	"userId" integer NOT NULL,
	"amount" integer NOT NULL,
	"currency" varchar(3) DEFAULT 'USD' NOT NULL,
	"status" "upside_transaction_status" DEFAULT 'completed' NOT NULL,
	"category" varchar(128) NOT NULL,
	"memo" varchar(512),
	"receiptUrl" varchar(512),
	"transactionDate" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"role" varchar(64) DEFAULT 'employee' NOT NULL,
	"department" varchar(128) DEFAULT 'General' NOT NULL,
	"avatarUrl" varchar(512),
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "upside_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "upside_card" ADD CONSTRAINT "upside_card_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_reimbursement" ADD CONSTRAINT "upside_reimbursement_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_transaction" ADD CONSTRAINT "upside_transaction_cardId_upside_card_id_fk" FOREIGN KEY ("cardId") REFERENCES "public"."upside_card"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_transaction" ADD CONSTRAINT "upside_transaction_merchantId_upside_merchant_id_fk" FOREIGN KEY ("merchantId") REFERENCES "public"."upside_merchant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_transaction" ADD CONSTRAINT "upside_transaction_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bill_status_idx" ON "upside_bill" USING btree ("status");--> statement-breakpoint
CREATE INDEX "card_user_idx" ON "upside_card" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "reimb_user_idx" ON "upside_reimbursement" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "tx_user_idx" ON "upside_transaction" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "tx_card_idx" ON "upside_transaction" USING btree ("cardId");--> statement-breakpoint
CREATE INDEX "tx_date_idx" ON "upside_transaction" USING btree ("transactionDate");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "upside_user" USING btree ("email");