CREATE TABLE "upside_early_signup" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_early_signup_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "early_signup_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "upside_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "early_signup_email_idx" ON "upside_early_signup" USING btree ("email");--> statement-breakpoint
CREATE INDEX "name_idx" ON "upside_post" USING btree ("name");