CREATE TYPE "public"."upside_api_key_status" AS ENUM('active', 'revoked');--> statement-breakpoint
CREATE TYPE "public"."upside_link_status" AS ENUM('active', 'disabled', 'expired');--> statement-breakpoint
CREATE TYPE "public"."upside_link_type" AS ENUM('receipt_scanner', 'order_pool', 'fund_request');--> statement-breakpoint
CREATE TYPE "public"."upside_webhook_status" AS ENUM('active', 'failing', 'disabled');--> statement-breakpoint
CREATE TABLE "upside_api_key" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_api_key_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"keyPrefix" varchar(32) NOT NULL,
	"status" "upside_api_key_status" DEFAULT 'active' NOT NULL,
	"scopes" text[] DEFAULT '{}'::text[] NOT NULL,
	"lastUsedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_integration_link" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_integration_link_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"name" varchar(256) NOT NULL,
	"type" "upside_link_type" NOT NULL,
	"description" varchar(512),
	"slug" varchar(128) NOT NULL,
	"status" "upside_link_status" DEFAULT 'active' NOT NULL,
	"submissions" integer DEFAULT 0 NOT NULL,
	"expiresAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_webhook" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_webhook_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"url" varchar(512) NOT NULL,
	"events" text[] DEFAULT '{}'::text[] NOT NULL,
	"status" "upside_webhook_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "upside_bill" ADD COLUMN "userId" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "upside_user" ADD COLUMN "kindeId" varchar(256);--> statement-breakpoint
ALTER TABLE "upside_api_key" ADD CONSTRAINT "upside_api_key_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_integration_link" ADD CONSTRAINT "upside_integration_link_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_webhook" ADD CONSTRAINT "upside_webhook_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "api_key_user_idx" ON "upside_api_key" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "integration_link_user_idx" ON "upside_integration_link" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "integration_link_slug_idx" ON "upside_integration_link" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "webhook_user_idx" ON "upside_webhook" USING btree ("userId");--> statement-breakpoint
ALTER TABLE "upside_bill" ADD CONSTRAINT "upside_bill_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "bill_user_idx" ON "upside_bill" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_kinde_id_idx" ON "upside_user" USING btree ("kindeId");--> statement-breakpoint
ALTER TABLE "upside_user" ADD CONSTRAINT "upside_user_kindeId_unique" UNIQUE("kindeId");