CREATE TABLE "upside_organization_member" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_organization_member_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"userId" integer NOT NULL,
	"role" varchar(32) DEFAULT 'member' NOT NULL,
	"canViewTransactions" boolean DEFAULT true NOT NULL,
	"canCreateCards" boolean DEFAULT false NOT NULL,
	"canSubmitReimbursements" boolean DEFAULT true NOT NULL,
	"canViewBills" boolean DEFAULT false NOT NULL,
	"canManageIntegrations" boolean DEFAULT false NOT NULL,
	"spendLimit" integer,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_organization" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_organization_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"slug" varchar(256) NOT NULL,
	"logoUrl" varchar(512),
	"type" varchar(32) DEFAULT 'personal' NOT NULL,
	"ownerId" integer NOT NULL,
	"setupComplete" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	CONSTRAINT "upside_organization_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "upside_organization_member" ADD CONSTRAINT "upside_organization_member_organizationId_upside_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_organization_member" ADD CONSTRAINT "upside_organization_member_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_organization" ADD CONSTRAINT "upside_organization_ownerId_upside_user_id_fk" FOREIGN KEY ("ownerId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "org_member_org_idx" ON "upside_organization_member" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "org_member_user_idx" ON "upside_organization_member" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "org_owner_idx" ON "upside_organization" USING btree ("ownerId");--> statement-breakpoint
CREATE INDEX "org_slug_idx" ON "upside_organization" USING btree ("slug");