-- Role status enum and roles table for Hire / job board posting
CREATE TYPE "upside_role_status" AS ENUM('draft', 'open', 'closed');

CREATE TABLE IF NOT EXISTS "upside_role" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "organizationId" integer NOT NULL,
  "createdBy" integer NOT NULL,
  "title" varchar(256) NOT NULL,
  "description" text NOT NULL,
  "department" varchar(128),
  "location" varchar(256),
  "status" "upside_role_status" DEFAULT 'open' NOT NULL,
  "postedTo" text[] DEFAULT '{}' NOT NULL,
  "postedAt" timestamp with time zone,
  "createdAt" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS "role_org_idx" ON "upside_role" ("organizationId");
CREATE INDEX IF NOT EXISTS "role_created_by_idx" ON "upside_role" ("createdBy");

ALTER TABLE "upside_role" ADD CONSTRAINT "upside_role_organizationId_organization_id_fk" 
  FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "upside_role" ADD CONSTRAINT "upside_role_createdBy_user_id_fk" 
  FOREIGN KEY ("createdBy") REFERENCES "public"."upside_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
