-- Card requests: personal users request a card from an org; org owner can issue or deny
CREATE TYPE "upside_card_request_status" AS ENUM('pending', 'issued', 'denied');

CREATE TABLE IF NOT EXISTS "upside_card_request" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "userId" integer NOT NULL,
  "organizationId" integer NOT NULL,
  "status" "upside_card_request_status" DEFAULT 'pending' NOT NULL,
  "requestedAt" timestamp with time zone DEFAULT now() NOT NULL,
  "processedAt" timestamp with time zone,
  "processedBy" integer
);

CREATE INDEX IF NOT EXISTS "card_request_user_idx" ON "upside_card_request" ("userId");
CREATE INDEX IF NOT EXISTS "card_request_org_idx" ON "upside_card_request" ("organizationId");

ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_userId_user_id_fk"
  FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_organizationId_organization_id_fk"
  FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_processedBy_user_id_fk"
  FOREIGN KEY ("processedBy") REFERENCES "public"."upside_user"("id") ON DELETE SET NULL ON UPDATE NO ACTION;
