CREATE TYPE "public"."upside_card_request_status" AS ENUM('pending', 'issued', 'denied');--> statement-breakpoint
CREATE TYPE "public"."upside_role_status" AS ENUM('draft', 'open', 'closed');--> statement-breakpoint
CREATE TABLE "upside_card_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_card_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"organizationId" integer NOT NULL,
	"status" "upside_card_request_status" DEFAULT 'pending' NOT NULL,
	"requestedAt" timestamp with time zone NOT NULL,
	"processedAt" timestamp with time zone,
	"processedBy" integer
);
--> statement-breakpoint
CREATE TABLE "upside_conversation_participant" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_conversation_participant_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" integer NOT NULL,
	"userId" integer NOT NULL,
	"lastReadAt" timestamp with time zone,
	"joinedAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_conversation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_conversation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lastMessageAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"conversationId" integer NOT NULL,
	"senderId" integer NOT NULL,
	"body" text NOT NULL,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"organizationId" integer,
	"type" varchar(64) DEFAULT 'system' NOT NULL,
	"title" varchar(512) NOT NULL,
	"body" text,
	"link" varchar(512),
	"readAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "upside_role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "upside_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"organizationId" integer NOT NULL,
	"createdBy" integer NOT NULL,
	"title" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"department" varchar(128),
	"location" varchar(256),
	"status" "upside_role_status" DEFAULT 'open' NOT NULL,
	"posted_to" text[] DEFAULT '{}'::text[] NOT NULL,
	"postedAt" timestamp with time zone,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "upside_card" ADD COLUMN "organizationId" integer;--> statement-breakpoint
ALTER TABLE "upside_card" ADD COLUMN "lithicCardToken" varchar(64);--> statement-breakpoint
ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_organizationId_upside_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_card_request" ADD CONSTRAINT "upside_card_request_processedBy_upside_user_id_fk" FOREIGN KEY ("processedBy") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_conversation_participant" ADD CONSTRAINT "upside_conversation_participant_conversationId_upside_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."upside_conversation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_conversation_participant" ADD CONSTRAINT "upside_conversation_participant_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_message" ADD CONSTRAINT "upside_message_conversationId_upside_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."upside_conversation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_message" ADD CONSTRAINT "upside_message_senderId_upside_user_id_fk" FOREIGN KEY ("senderId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_notification" ADD CONSTRAINT "upside_notification_userId_upside_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_notification" ADD CONSTRAINT "upside_notification_organizationId_upside_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_role" ADD CONSTRAINT "upside_role_organizationId_upside_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upside_role" ADD CONSTRAINT "upside_role_createdBy_upside_user_id_fk" FOREIGN KEY ("createdBy") REFERENCES "public"."upside_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "card_request_user_idx" ON "upside_card_request" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "card_request_org_idx" ON "upside_card_request" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "conv_part_conv_idx" ON "upside_conversation_participant" USING btree ("conversationId");--> statement-breakpoint
CREATE INDEX "conv_part_user_idx" ON "upside_conversation_participant" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "message_conv_idx" ON "upside_message" USING btree ("conversationId");--> statement-breakpoint
CREATE INDEX "message_created_idx" ON "upside_message" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "notification_user_idx" ON "upside_notification" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "notification_read_idx" ON "upside_notification" USING btree ("readAt");--> statement-breakpoint
CREATE INDEX "notification_created_idx" ON "upside_notification" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "role_org_idx" ON "upside_role" USING btree ("organizationId");--> statement-breakpoint
CREATE INDEX "role_created_by_idx" ON "upside_role" USING btree ("createdBy");--> statement-breakpoint
ALTER TABLE "upside_card" ADD CONSTRAINT "upside_card_organizationId_upside_organization_id_fk" FOREIGN KEY ("organizationId") REFERENCES "public"."upside_organization"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "card_org_idx" ON "upside_card" USING btree ("organizationId");